- name: Install package
  apt: name=nginx state=present
  tags: nginx

- name: Copy nginx site
  copy: src=nginx_route.site dest=/etc/nginx/sites-available/route
  notify: restart nginx
  tags: nginx

- name: Enable site
  file: src=/etc/nginx/sites-available/route dest=/etc/nginx/sites-enabled/route state=link
  notify: restart nginx
  tags: nginx

- name: Disable default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
  tags: nginx
