---
- hosts: tv-h
  become: yes
  vars:
    downloads_group: downloads
  tasks:
    - name: Install packages
      apt: name={{item}} update_cache=yes state=present
      with_items:
        - python
        - git
        - vim
        - tmux
        - avahi-daemon

    - name: Disable suspend on lid close
      lineinfile: regexp=HandleLidSwitch= line="HandleLidSwitch=ignore" path=/etc/systemd/logind.conf
      notify: restart logind
  roles:
    - role: external_hdd
      owner_group: " {{ downloads_group }}"
    - role: transmission
      secondary_groups: "{{ downloads_group }}"
    - role: couchpotato
      group: "{{ downloads_group }}"
    - role: sickrage
      group: "{{ downloads_group }}"
    - nginx
  handlers:
      - name: restart logind
        service: name=systemd-logind state=restarted
