---
- hosts: tv-h
  become: yes
  vars:
    downloads_group: downloads
  tasks:
    - name: Install packages
      apt: name={{item}} update_cache=yes state=present
      with_items:
        - python
        - git
        - vim
        - tmux
        - nginx
        - avahi-daemon

    - name: Create mount point
      file: name=/mnt/downloads state=directory

    - name: Mount downloads dir
      mount: name=/mnt/downloads fstype=ext4 src=LABEL=Downloads state=present

    - name: Create downloads group
      group: name=downloads gid=125 state=present
        
    - name: Copy nginx site
      copy: src=config/nginx_route.site dest=/etc/nginx/sites-available/route
      notify: restart nginx
      tags: nginx

    - name: Enable site
      file: src=/etc/nginx/sites-available/route dest=/etc/nginx/sites-enabled/route state=link
      notify: restart nginx
      tags: nginx

    - name: Disable default nginx site
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify: restart nginx
      tags: nginx

    - name: Disable suspend on lid close
      lineinfile: regexp=HandleLidSwitch= line="HandleLidSwitch=ignore" path=/etc/systemd/logind.conf
      notify: restart logind
  roles:
    - role: transmission
      secondary_groups: "{{ downloads_group }}"
    - role: couchpotato
      group: "{{ downloads_group }}"
    - role: sickrage
      group: "{{ downloads_group }}"
  handlers:
      - name: restart nginx
        service: name=nginx enabled=yes state=restarted
      - name: restart logind
        service: name=systemd-logind state=restarted
