---
- hosts: tv-h
  become: yes
  vars:
    daemons:
      couchpotato: https://github.com/CouchPotato/CouchPotatoServer
      sickrage: https://github.com/SickRage/SickRage
      #headphones: https://github.com/rembo10/headphones.git
  tasks:
    - name: Install packages
      apt: name={{item}} update_cache=yes state=present
      with_items:
        - python
        - git
        - vim
        - tmux
        - transmission-daemon
        - nginx
        - avahi-daemon
        - nodejs-legacy # sickrage searches need this

    - name: Create mount point
      file: name=/mnt/downloads state=directory

    - name: Mount downloads dir
      mount: name=/mnt/downloads fstype=ext4 src=LABEL=Downloads state=present

    - name: Create downloads group
      group: name=downloads gid=125 state=present

    - name: Create daemon users
      user: name={{item}} group=downloads home=/opt/{{item}} createhome=no
      with_items: "{{ daemons }}"
        
    - name: Put transmission in downloads group
      user: name=debian-transmission groups=downloads append=yes
      notify: restart transmission

    - name: Create daemon dirs
      file: name=/opt/{{item}} owner={{item}} group=downloads state=directory
      with_items: "{{daemons}}"

    - name: Install daemons
      git: repo={{item.value}} dest=/opt/{{item.key}} accept_hostkey=yes
      become_user: "{{item.key}}"
      with_dict: "{{daemons}}"
      notify: restart {{item.key}}

    - name: Copy init scripts
      copy: src=init/{{item}}.service dest=/lib/systemd/system/
      with_items: "{{daemons}}"
      notify: restart {{item}}

    - name: Copy daemon config
      copy: src={{item}} dest=/etc/default/{{item|basename}}
      with_fileglob: 'deamon_config/*'
      notify: restart {{item|basename}}

    - name: Copy transmission config
      copy: src=config/transmission.settings.json dest=/etc/transmission-daemon/settings.json owner=debian-transmission group=debian-transmission mode=0600
      notify: restart transmission
      tags: transmission
    
    - name: Copy nginx site
      copy: src=config/nginx_route.site dest=/etc/nginx/sites-available/route
      notify: restart nginx
      tags: nginx

    - name: Enable site
      file: src=/etc/nginx/sites-available/route dest=/etc/nginx/sites-enabled/route state=link
      notify: restart nginx
      tags: nginx

    - name: Disable default nginx site
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify: restart nginx
      tags: nginx

    - name: Disable suspend on lid close
      lineinfile: regexp=HandleLidSwitch= line="HandleLidSwitch=ignore" path=/etc/systemd/logind.conf
      notify: restart logind
  handlers:
      - name: restart couchpotato
        service: name=couchpotato enabled=yes state=restarted
      - name: restart sickrage
        service: name=sickrage enabled=yes state=restarted
        #      - name: restart headphones
        #        service: name=headphones enabled=yes state=restarted
      - name: restart transmission
        service: name=transmission-daemon enabled=yes state=restarted
      - name: restart nginx
        service: name=nginx enabled=yes state=restarted
      - name: restart logind
        service: name=systemd-logind state=restarted
