---
# tasks file for sickchill
- block:
  - name: Install required packages
    apt: name=nodejs,python3-pip,python3-venv state=present

  - name: Create user
    user: name={{username}} group={{group}} home={{homedir}} createhome=no

  - name: Create daemon dir
    file: name={{homedir}} owner={{username}} group={{group}} state=directory

  - name: Create venv
    command: python3 -m venv {{homedir}}
    become_user: "{{username}}"

  - name: Install
    pip:
      virtualenv: "{{homedir}}"
      state: present
      name: sickchill
    become_user: "{{username}}"

  - name: Copy init script
    get_url:
      url: https://raw.githubusercontent.com/SickChill/sickchill/master/contrib/runscripts/init.systemd
      dest: /etc/systemd/system/sickchill.service
    notify: restart sickchill

  - name: Patch group name
    lineinfile: path=/etc/systemd/system/sickchill.service regexp="Group=sickchill" line="Group={{group}}" state=present

  - name: Enable service
    service: name=sickchill enabled=yes state=started
  tags: sickchill
