---
username: duplicati
user_id: 0 # Dont override uid by default
group: duplicati
group_id: 0 # Dont override gid by default
homedir: /var/lib/duplicati

artifact_url: "https://github.com/duplicati/duplicati/releases/download/v2.3.0.1_stable_2026-04-24/duplicati-2.3.0.1_stable_2026-04-24-linux-x64-cli.deb"

listen_port: 8200
listen_interface: any
extra_opts: ""
