---
# tasks file for roles/transmission
- block:
  - name: Install pacakge
    apt: name=transmission-daemon state=present

  - name: Stop service
    service: name=transmission-daemon state=stopped

  - name: Put transmission in downloads group
    user: name=debian-transmission groups={{secondary_groups}} append=yes
    when: (secondary_groups)

  - name: Copy transmission config
    copy: src=transmission.settings.json dest=/etc/transmission-daemon/settings.json owner=debian-transmission group=debian-transmission mode=0600

  - name: Start service
    service: name=transmission-daemon state=started
  tags: transmission

