---
- block:
  - name: Create group
    group: name={{group}} gid={{group_id or omit}}

  - name: Create user
    user: name={{username}} uid={{user_id or omit}} group={{group}} home={{homedir}} createhome=yes

  - name: Downoad and install duplicati
    apt: deb={{artifact_url}} state=present
    notify: restart duplicati
      
  - name: Ensure drop-in directory of systemd service is created
    file:
      path: /etc/systemd/system/duplicati.service.d/
      state: directory
      mode: '0755'

  - name: copy systemd drop-in
    template: src=systemd-nonroot.conf.j2 dest=/etc/systemd/system/duplicati.service.d/nonroot.conf

  - name: copy config
    template: src=duplicati-config.j2 dest=/etc/default/duplicati
    notify: restart duplicati

  - name: Start duplicati
    systemd_service: name=duplicati state=started enabled=yes daemon_reload=yes
  tags: duplicati
  become: true
