---
- name: Add mono repo key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: Add mono repo
  apt_repository:
    repo: deb https://download.mono-project.com/repo/ubuntu stable-bionic main
    state: present

- name: Install mono
  apt: name=mono-devel,ca-certificates-mono update_cache=yes state=present
