- name: Install packages
  apt: name={{item}} update_cache=yes state=present
  with_items:
    - python3
    - git
    - vim
    - tmux
    - acl
    
- name: Create logind.conf.d
  file: path=/etc/systemd/logind.conf.d state=directory

- name: Disable suspend on lid close
  copy:
    content: |
      [Login]
      HandleLidSwitch=ignore
    dest: /etc/systemd/logind.conf.d/disable_lid_sleep.conf
  notify: restart logind
    
- name: Create network config dir
  file: path=/etc/systemd/network state=directory

## this may require disabling netplan and its installed networkd config to work
- name: Enable mDNS for {{ eth_interface }}
  template:
    src: systemd_eth_config.network
    dest: /etc/systemd/network/10-{{eth_interface}}.network
  notify: reload networkd
