---
# tasks file for couchpotato
- name: Create user
  user: name={{username}} group={{group}} home={{homedir}} craetehome=no

- name: Create daemon dir
  file: name={{homedir}} owner={{username}} group={{group}} state=directory

- name: Install daemon
  git: repo={{repo_url}} dest={{homedir}} accept_hostkey=yes
  become_user: "{{username}}"
  notify: restart couchpotato

- name: Copy init script
  template: couchpotato.service dest=/lib/systemd/system/
  notify: restart couchpotato
