- name: Install wireguard
  apt:
    name: wireguard
    state: present
  become: true

- name: Configure wg0 interface
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: 0600
    owner: root
    group: root
  notify: Reload wg0 interface
  become: true

- name: Bring up wg0 interface
  service:
    name: wg-quick@wg0
    state: started
    enabled: true
  become: true

