---
# tasks file for sickrage
- block:
  - name: Install required packages
    apt: name=nodejs,python-pip state=present

  - name: Create user
    user: name={{username}} group={{group}} home={{homedir}} createhome=no

  - name: Create daemon dir
    file: name={{homedir}} owner={{username}} group={{group}} state=directory

  - name: Git clone
    git: repo={{repo_url}} dest={{homedir}} accept_hostkey=yes
    become_user: "{{username}}"
    notify: restart sickrage

  - name: Install
    command: pip install -r {{homedir}}/requirements.txt
    notify: restart sickrage

  - name: Install config file
    copy: src=sickrage.conf dest=/etc/default/sickrage
    notify: restart sickrage

  - name: Copy init script
    template: src=sickrage.service dest=/lib/systemd/system/
    notify: restart sickrage
  tags: sickrage
